name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*'
      - 'build.yaml'

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr-full
      # ↓ここに「Nix環境を使うな」という絶対命令を追加します
      use_nix: false
